### ISSUE TITLE
REBLUR VS. RELAX

### ISSUE THREAD

**Issue by wangyuehi** [NVIDIAGameWorks/RayTracingDenoiser#47]
Hi,

Maybe I missed it, but is there any recommendation between REBLUR vs. RELAX, for example, which denoising method works better in which case, in terms of diffuse signals?

Thanks

**Comment by dzhdanNV** [comment]
Hi,

Apologies for the delay.

REBLUR:
- 25% faster (can be made even more faster in exchange of IQ if temporal stabilization is disabled and/or performance mode is enabled)
- in some cases more temporally stable
- coupled with AO / SO denoising (i.e. AO denoising is a free addition to the diffuse denoiser)

RELAX:
- has luminance stoppers (no luminance stoppers in REBLUR)
- dense spatial filtering (A-trous decomposition) in some cases provides advantages over sparse filtering in REBLUR

Of course, there are corner cases when one denoiser works better than another. In some cases it depends only on personal preference. Integrate NRD, allow real-time switching, choose one, which works best for you.

**Comment by wangyuehi** [comment]
alright, thanks a lot for the info!
