### ISSUE TITLE
the value of m_JitterDelta

### ISSUE THREAD

**Issue by wangyuehi** [NVIDIAGameWorks/RayTracingDenoiser#48]
Hi

I had a question while integrating NRD v3.7.0:

The value of m_JitterDelta:
As far as I see in DenoiserImpl.cpp : 654:
```
    float dx = ml::Abs(m_CommonSettings.cameraJitter[0] - m_JitterPrev.x);
    float dy = ml::Abs(m_CommonSettings.cameraJitter[1] - m_JitterPrev.y);
    m_JitterDelta = ml::Max(dx, dy);
```
but DenoiserImpl.cpp : 506:
```
    m_JitterPrev = ml::float2(m_CommonSettings.cameraJitter[0], m_CommonSettings.cameraJitter[1]);
```

it looks like m_JitterDelta will always be 0 since `dx` and `dy` are 0? or maybe I missed something?

Thanks

**Comment by dzhdanNV** [comment]
`m_JitterPrev` is the previous jitter, it gets saved when `m_CommonSettings` is in the previous state. After this `m_CommonSettings` gets updated to the current values. Works as expected.
