### ISSUE TITLE
Texture clear dispatch thread count issue

### ISSUE THREAD

**Issue by gaetan-deturche** [NVIDIAGameWorks/RayTracingDenoiser#53]
Hi,
For non pool textures, width size of the clear command is init to the height of the texture in DenoiserImpl.cpp line 924
Regards

**Comment by dzhdanNV** [comment]
@gaetan-deturche Many thanks! Yeah, sorry for the silly mistake. Fixed locally. GitHub is not updated yet.

**Comment by dzhdanNV** [comment]
@gaetan-deturche Appreciate your help! Fixed!
