### ISSUE TITLE
Specular reflections for pure mirrors

### ISSUE THREAD

**Issue by Zwingling** [NVIDIAGameWorks/RayTracingDenoiser#62]
What is the best way to achieve detailed specular reflections on perfect mirrors (roughness = 0). Using Relax/Reblur still adds some blur in this case. Should I fallback to the un-denoised image in that case?

**Comment by dzhdanNV** [comment]
Do you mind attaching a problematic part of a screenshot taking in motion for more substantive conversation?

**Comment by h-mathias** [comment]
Sure, here is a screenshot where left is the un-denoised image and right the denoised one(Relax).
![Specular](https://github.com/NVIDIAGameWorks/RayTracingDenoiser/assets/7537910/04b838cd-144a-4ad8-a4aa-b90e02a8f0f3)

**Comment by dzhdanNV** [comment]
It's worth comparing with REBLUR at least as a new data point. In your case reflections in pure mirrors are not noisy, i.e. accumulation is not needed. REBLUR has `responsiveAccumulationRoughnessThreshold` option, which allows to minimize accumulation for surfaces with roughness below the threshold.

**Comment by h-mathias** [comment]
Thanks, REBLUR indeed results in less blur and using the un-denoised image as fallback for RELAX also works for me.
