### ISSUE TITLE
More Cmake Options for Compiling Shaders to Different Backends

### ISSUE THREAD

**Issue by Sirtsu55** [NVIDIAGameWorks/RayTracingDenoiser#63]
It would be nice to have more control over precompiled shaders and what backend they are compiled for. For example, not every Win32 application uses DXIL shaders or SPIR-V; therefore, having more control over what shaders are compiled would be great. Right now the assumption is that for Win32 application shaders are compiled to all backends, even though those aren't necessarily used.

I could add a PR addressing the issue/enhancement if that is okay.
Thanks

**Comment by dzhdanNV** [comment]
Yes, create a PR, please. The logic behind the current solution is:
- compilation time is limited by DXBC code gen. Depending on CPU it's 2 secs for DXIL/SPIRV and 15 secs for DXBC
- re-compilation after some changes (not in main shared headers) is just fast
- minimizing support burden

But if your request is easy to implement & support... why not?

**Comment by Sirtsu55** [comment]
PR Opened: #64

**Comment by dzhdanNV** [comment]
Testing...

**Comment by dzhdanNV** [comment]
Thanks! Integrated! Note, that I fixed typos, auto-formatted the file and refactored a bit in my local version. My edited version will sneak on GitHub with the next update.

Logically, the next step would be to introduce more explicit:
```
NRD_HAS_SPIRV_SHADERS
NRD_HAS_DXBC_SHADERS
NRD_HAS_DXIL_SHADERS
```
instead of `hard-to-follow-what's-going-on-here`:
```
NRD_USE_PRECOMPILED_SHADERS
NRD_PRECOMPILE_SPIRV_SHADERS
NRD_PRECOMPILE_D3D_SHADERS
NRD_ONLY_SPIRV_SHADERS_AVAILABLE
```
Let me know what you think...

**Comment by Sirtsu55** [comment]
Yes, sounds great! I'm a bit unfamiliar with the codebase so I opted to just separate into D3D and SPIR-V. The specifics would be a great addition. Let's close the issue once you add the new options.

**Comment by dzhdanNV** [comment]
@Sirtsu55 Implemented! Please, review this Cmake file (I also made a ton of changes in `cpp` files, but you definitely don't want to see them): [CMakeLists.txt](https://github.com/NVIDIAGameWorks/RayTracingDenoiser/files/11665364/CMakeLists.txt)

**Comment by dzhdanNV** [comment]
Reworked a bit:
```
option (NRD_EMBEDS_SPIRV_SHADERS "NRD embeds SPIRV shaders" ON)
option (NRD_EMBEDS_DXIL_SHADERS "NRD embeds DXIL shaders" ${IS_WIN})
option (NRD_EMBEDS_DXBC_SHADERS "NRD embeds DXBC shaders" ${IS_WIN})
option (NRD_DISABLE_SHADER_COMPILATION "Disable shader compilation" OFF)
```
- First 3 options dictate which types of shaders to compile and embed into the binary
- last option explicitly disables shader compilation completely on the NRD side, NRD assumes that shaders are compiled according to `NRD_EMBEDS_...` settings and have been put into `NRD_SHADERS_PATH` folder
[CMakeLists.txt](https://github.com/NVIDIAGameWorks/RayTracingDenoiser/files/11665623/CMakeLists.txt)

**Comment by Sirtsu55** [comment]
Nice implementation! I noticed you added --useAPI to to the general arguments, so the linux build could fail because the ShaderMake docs say it's Windows-only. Apart from that, thanks for implementing this.

**Comment by dzhdanNV** [comment]
Yes! Will fix right now... Argh!

**Comment by dzhdanNV** [comment]
With the fix: 
[CMakeLists.txt](https://github.com/NVIDIAGameWorks/RayTracingDenoiser/files/11665695/CMakeLists.txt)

Do you give your blessing? ;)

**Comment by Sirtsu55** [comment]
Looks good. Bless the CMake! :)

**Comment by dzhdanNV** [comment]
Thanks! It will be included into the next release (next week I hope).

**Comment by dzhdanNV** [comment]
Implemented!
