### ISSUE TITLE
Build Failed:  'REBLUR/REBLUR_DiffuseSpecular_TemporalAccumulation.hlsli' file not found

### ISSUE THREAD

**Issue by kumozheng** [NVIDIAGameWorks/RayTracingDenoiser#70]
When I build NRD.sln，occur those error:
fatal error: 'REBLUR/REBLUR_DiffuseSpecular_TemporalAccumulation.hlsli' file not found
fatal  error C1083: Cannot open include file: 'Clear_f.cs.dxbc.h': No such file or directory
fatal  error C1083: Cannot open include file: 'REFERENCE_TemporalAccumulation.cs.dxbc.h': No such file or directory
fatal  error C1083: Cannot open include file: 'REBLUR_ClassifyTiles.cs.dxbc.h': No such file or directory

**Comment by dzhdanNV** [comment]
I did clean clone. It works. GitHub automation compiled NRD on Windows and Linux too.

**Comment by djbelyak** [comment]
@kumozheng looks like your version of `NRD.sln` is out of sync with the rest project.
Could you, please, execute [the update instruction](https://github.com/NVIDIAGameWorks/RayTracingDenoiser#how-to-update) and try to open `NRD.sln` once again?

**Comment by kumozheng** [comment]
@dzhdanNV @djbelyak 
Thanks replys. I have solved this build failure as following: 
 method 1: delete that comment in REBLUR/REBLUR_DiffuseSpecular_TemporalAccumulation.hlsli
![1](https://github.com/NVIDIAGameWorks/RayTracingDenoiser/assets/24120577/389beda6-8f7d-48b0-9c72-cb8509c96b93)
method2:  Windows Region Setting  
![2](https://github.com/NVIDIAGameWorks/RayTracingDenoiser/assets/24120577/a3728ad4-6a23-4ce0-9e00-c246151622fd)

**Comment by dzhdanNV** [comment]
Wow! I thought UNICODE symbols are supported everywhere nowadays. This emoji does describe the situation best. But, ok, I will replace it with something more portable (the fix will be included into the next update). Really appreciate the effort! Thanks! :D
