### ISSUE TITLE
Which NRI version to use with current NRD master branch?

### ISSUE THREAD

**Issue by StudenteChamp2** [NVIDIAGameWorks/RayTracingDenoiser#81]
I am adding NRD support to my raytracer. I successfully built the library.
When i follow the steps on github i need to include theses files:
![Missing](https://github.com/user-attachments/assets/c4f8ee2e-dd1f-445f-96d6-725744ad5265)

They are missing. I found out they are located in another repository
https://github.com/NVIDIAGameWorks/NRI

But which version to choose? I am using the master branch of NRD

**Comment by StudenteChamp2** [comment]
Tried the master branch of NRI. When i compile my app I get errors like this : **nrdintegration.h(77): error C2039: 'CoreInterface': is not a member of 'nri'**  
![NRI_Errors](https://github.com/user-attachments/assets/67b44123-51fc-4b83-8411-5194d890a7d2)

**Comment by dzhdanNV** [comment]
You should include the main NRI header `NRI.h`. I will correct the docs.

**Comment by StudenteChamp2** [comment]
Build passes now thank you :)
