### ISSUE TITLE
Is NRD limited to 16 bits float textures?

### ISSUE THREAD

**Issue by StudenteChamp2** [NVIDIAGameWorks/RayTracingDenoiser#83]
From NRD.hlsli:

		// X => IN_DIFF_RADIANCE_HITDIST
		// X => IN_SPEC_RADIANCE_HITDIST
		float4 RELAX_FrontEnd_PackRadianceAndHitDist( float3 radiance, float hitDist, bool sanitize )
		{
  		  if( sanitize )
    		{
      		  radiance = _NRD_IsInvalid( radiance ) ? float3( 0, 0, 0 ) : clamp( radiance, 0, NRD_FP16_MAX );
      		  hitDist = _NRD_IsInvalid( hitDist ) ? 0 : clamp( hitDist, 0, NRD_FP16_MAX );
    		}

   		 return float4( radiance, hitDist );
		}
		
What will happen if i use 32 bits float textures?

**Comment by dzhdanNV** [comment]
> What will happen if i use 32 bits float textures?

You can use FP32 if your radiance passed to NRD <= NRD_FP16_MAX.

> Is NRD limited to 16 bits float textures?

Internal processing for radiance is FP16. But when creating NRD resources, including internal ones, you can replace `RGBA16f` to `RGBA32f` without problems. It can be done by modifying `g_NRD_NrdToNriFormat`, if you use the NRD integration layer.

**Comment by StudenteChamp2** [comment]
Exellent thank you <3

**Comment by dzhdanNV** [comment]
NRD integration layer now supports FP16/FP32 promotion/demotion:
```
    // Demote FP32 to FP16 (slightly improves performance in exchange of precision loss)
    // (FP32 is used only for viewZ under the hood, all denoisers are FP16 compatible)
    bool demoteFloat32to16 = false;

    // Promote FP16 to FP32 (overkill, kills performance)
    bool promoteFloat16to32 = false;
```
Rarely needed, but still...
