### ISSUE TITLE
How to  properly create an NrdIntegrationTexture given a ID3D12Resource?

### ISSUE THREAD

**Issue by StudenteChamp2** [NVIDIAGameWorks/RayTracingDenoiser#84]
Now i have this:

			NrdIntegrationTexture In_NRD_DiffuseRadianceHitTexture = {};
			nri::TextureD3D12Desc textureDesc = {};
			textureDesc.d3d12Resource = In_Native_DiffuseRadianceHitTexture.buffer;//In_Native_DiffuseRadianceHitTexture.buffer is ID3D12Resource*

			// Then what?
			//m_NRI.CreateTextureD3D12(*m_nriDevice, textureDesc, (nri::Texture*&)In_NRD_DiffuseRadianceHitTexture.state->texture);
			
Can't use since In_NRD_DiffuseRadianceHitTexture.state since NULL and even if it was not the m_NRI.CreateTextureD3D12 call doesnt fully initialize the integration texture. What is the state of the Art way to do it?
			
Thank you!

**Comment by dzhdanNV** [comment]
Scroll down to `WRAP NATTIVE POINTERS`:
https://github.com/NVIDIAGameWorks/RayTracingDenoiser?tab=readme-ov-file#variant-3-black-box-library-using-native-api-pointers

In short:
- wrap your texture (create an NRI object)
- `NrdIntegrationTexture` consists of `state` and `format`
- fill in `format`, which you know (I will remove `format` in the future, since it can be queried via NRI)
- fill in `state`, which you know too

You can follow the NRD sample logic. The only difference is wrapping vs creation.

**Comment by StudenteChamp2** [comment]
Thank you for being quick to answer. It is appreciated <3

**Comment by StudenteChamp2** [comment]
nri::TextureBarrierDesc entryDesc;

			nri::TextureD3D12Desc textureDesc = {};
			textureDesc.d3d12Resource = In_Native_DiffuseRadianceHitTexture.buffer;

			m_NRI.CreateTextureD3D12(*m_nriDevice, textureDesc, (nri::Texture*&)entryDesc.texture);


			entryDesc.after.access = nri::AccessBits::SHADER_RESOURCE;
			entryDesc.after.layout = <what to put here>? nri::Layout::UNKNOWN?
			
Also  nri::TextureBarrierDesc has other fields than just a a texture:

NriStruct(TextureBarrierDesc) {
    NriPtr(Texture) texture;
    Nri(AccessLayoutStage) before;
    Nri(AccessLayoutStage) after;
    Nri(Mip_t) mipOffset;
    Nri(Mip_t) mipNum;
    Nri(Dim_t) layerOffset;
    Nri(Dim_t) layerNum;
    Nri(PlaneBits) planes;
};

I guess mipOffset should be 0 and mipNum 1. But what about the remaining?

**Comment by dzhdanNV** [comment]
All can be 0. From NRI:
```
static const Nri(Mip_t) NriConstant(REMAINING_MIPS) = 0;    // only for "mipNum"
static const Nri(Dim_t) NriConstant(REMAINING_LAYERS) = 0;  // only for "layerNum"
PlaneBits::ALL = 0
```

**Comment by dzhdanNV** [comment]
NRD integration has been improved. `format` is not needed anymore.
