### ISSUE TITLE
How to get rid of NRI  initialization warnings

### ISSUE THREAD

**Issue by StudenteChamp2** [NVIDIAGameWorks/RayTracingDenoiser#85]
I am integrating NRD denoising in my software. But at NRI initialization i get warnings.

1) First i updated my solution to the **10.0.22621.0** windows SDK. Just to be sure it is not related to [this](https://github.com/NVIDIAGameWorks/NRDSample/issues/19)
https://youtu.be/YCSmtXtAq0s

2) Then i try to initialize NRI:
		nri::DeviceCreationD3D12Desc deviceDesc = {};
		deviceDesc.d3d12Device = m_cmdContext.device;
		deviceDesc.d3d12GraphicsQueue = m_cmdContext.commandQueue;
		deviceDesc.enableNRIValidation = true;
	
		nri::Result nriResult = nri::nriCreateDeviceFromD3D12Device(deviceDesc, m_nriDevice);

3) This line
		nri::Result nriResult = nri::nriCreateDeviceFromD3D12Device(deviceDesc, m_nriDevice);  
		
Gives me the following warnings:

**NRI::WARNING(D3DExt.hpp:29) - D3D12::NVIDIA GeForce RTX 3080 - d3d12::Ext::InitializeNVExt: NVAPI is disabled, because it's not loaded on the application side
NRI::INFO(DeviceD3D12.cpp:231) - D3D12::NVIDIA GeForce RTX 3080 - Using ID3D12Device5
NRI::WARNING(DeviceD3D12.cpp:287) - D3D12::NVIDIA GeForce RTX 3080 - nri::DeviceD3D12::FillDesc: ID3D12Device::CheckFeatureSupport(shaderModel) failed, result = 0x80070057!**

The SURPRISING thing is that i do not get the last warning on my RTX 3060. I only get this:
**NRI::WARNING(D3DExt.hpp:29) - D3D12::NVIDIA GeForce RTX 3060 Laptop GPU - d3d12::Ext::InitializeNVExt: NVAPI is disabled, because it's not loaded on the application side
NRI::INFO(DeviceD3D12.cpp:231) - D3D12::NVIDIA GeForce RTX 3060 Laptop GPU - Using ID3D12Device5**

**Comment by dzhdanNV** [comment]
> NVAPI is disabled, because it's not loaded on the application side

Please, ignore.

> ID3D12Device::CheckFeatureSupport(shaderModel) failed, result = 0x80070057!

Update NRI to the latest.

> First i updated my solution to the 10.0.22621.0 windows SDK

Hope you didn't forget to run "clean.bat" and "deploy.bat" scripts to hook up latest SDK.

> The SURPRISING thing is that i do not get the last warning on my RTX 3060

I'm not surprised. Since the laptop is a different machine, I have a gut feeling that the SDK / driver setup on the other machine is a bit broken.

**Comment by dzhdanNV** [comment]
The discussion is in stagnation. Closing, since it's not an NRD issue. Feel free to reopen, if there is a real need.
